### ISSUE TITLE
Reverse winding order for negatively scaled objects

### ISSUE THREAD

**Issue by tkazik** [CesiumGS/cesium#6304]
Hi folks

I have some models that contain negative scales (which originate from mirroring objects).
Attached you find a blender file, that contains three cubes:

- normal cube (left on following images)
- cube with flipped normals (centered on following images)
- cube scaled by -1 (right on following images)

Appearance in Cesium:
![cesium](https://user-images.githubusercontent.com/15689124/36936609-e03bb69a-1f07-11e8-9b7a-223f9034cf47.png)

Babylonjs:
![babylonjs](https://user-images.githubusercontent.com/15689124/36936622-11dc90c0-1f08-11e8-9965-4a92d593fc6e.png)

Threejs:
![threejs](https://user-images.githubusercontent.com/15689124/36936623-1353667c-1f08-11e8-9fe5-889bdce817b4.png)

Babylonjs and Threejs seem to handle the reversed winding order for negatively scaled objects correctly.
Is there a chance you can adapt Cesium to have the same behaviour? E.g. expect a reversed winding order for an odd number of negative scales in the gltf? 

The blend file and and gltfs (produced by the official khronos exporter) are here: 
[cubes.zip](https://github.com/AnalyticalGraphicsInc/cesium/files/1777661/cubes.zip)

PS: Relevant part of gltf:
![gltf](https://user-images.githubusercontent.com/15689124/36936796-ffb3cc40-1f09-11e8-96f8-5ffd60481a86.png)

**Comment by hpinkos** [comment]
Thanks @tkazik!

@lilleyse what do you think about this?

**Comment by lilleyse** [comment]
It's something we should fix evntually. The spec says

> Implementation Note: If the determinant of the transform is a negative value, the winding order of the mesh triangle faces should be reversed. This supports negative scales for mirroring geometry.

I started to make a fix in https://github.com/AnalyticalGraphicsInc/cesium/commit/07c3ad91a8c66fa19ce9b5ccc120ff9542cb673a but there were some complications - when we create the commands we don't know the computed matrices yet. I might get to it later instead.

**Comment by tkazik** [comment]
Just had a look at your suggestion:
```
if (rs.cull.enabled && Matrix4.determinant(runtimeNode.computedMatrix) < 0.0) {
    rs = clone(rs, true);
    rs.cull.face = (rs.cull.face === CullFace.BACK) ? CullFace.FRONT : CullFace.BACK;
    rs = RenderState.fromCache(rs);
}
```
The inner part of the if-statement never gets executed, as the `runtimeNode.computedMatrix` is a matrix of zeros and its determinant is thus also zero. Any ideas why that happens?

**Comment by lilleyse** [comment]
At that point the `computedMatrix` hasn't been computed yet. It's just an order of execution problem in our loader. I left the code in an unfinished state for now until I am able to look at it closer.

**Comment by tkazik** [comment]
Ok, thanks! I created a new PR, that seems to fix the issue. Basically, it takes the scales of the gltf node to determine the culling. Let me know what you think of it.

**Comment by tkazik** [comment]
Any updates?

**Comment by tkazik** [comment]
Hey guys, a 1.5 years have passed and I am wondering whether there is no interest in this issue. Any update? Thx!

**Comment by lilleyse** [comment]
@tkazik With the current design of `Model.js` I don't think we'll get to this soon. That said, we're thinking about ways to re-architect glTF loading as part of our push for 3D Tiles Next and we'll keep this issue in mind.

**Comment by emackey** [comment]
@lexaknyazev If glTF were tweaked to require `doubleSided` on any mesh with negative scales, this issue would become OBE and could be closed, I believe.

**Comment by pjcozzi** [comment]
> @tkazik With the current design of Model.js I don't think we'll get to this soon. That said, we're thinking about ways to re-architect glTF loading as part of our push for 3D Tiles Next and we'll keep this issue in mind.

@lilleyse does the upcoming Model.js refactor address this issue?

> @lexaknyazev If glTF were tweaked to require doubleSided on any mesh with negative scales, this issue would become OBE and could be closed, I believe.

@lexaknyazev what do you think of @emackey's proposal?

**Comment by lexaknyazev** [comment]
@pjcozzi 
It's a bit strange to introduce such a change now given that other engines seem to support the current spec language.

**Comment by emackey** [comment]
@lexaknyazev I was remembering a conversation about this during the keyword cleanup pass, I thought we had considered changing this anyway due to difficulty in getting correct language describing the behavior of single-sided inverted meshes.  Is that resolved now?

**Comment by pjcozzi** [comment]
@lexaknyazev @emackey thanks for the fast responses.  Current implementations aside, is this potentially a spec "bug" or unnecessary complexity?  If so, perhaps we should discuss with the working group?  If not, then CesiumJS should indeed be updated.

**Comment by lilleyse** [comment]
> @lilleyse does the upcoming Model.js refactor address this issue?

No, not yet.

**Comment by tkazik** [comment]
This is unfortunately still an issue for us and implies that we have to "fix" our models the modeling SW, which involves quite a lot of manual work. Thx for your consideration!

**Comment by lilleyse** [comment]
@tkazik thanks for bumping this issue. I spent a little time poking around `ModelExperimental` and it's a much easier fix there. Just need to write some unit tests and then I'll open a PR.

**Comment by lilleyse** [comment]
Fixed in https://github.com/CesiumGS/cesium/pull/10405 - though you'll need to use `ModelExperimental` instead of `Model` until we're ready to replace the old `Model` in a couple months.

**Comment by tkazik** [comment]
That is great and exciting news! 🙌🥳
